# Generated by Django 5.2.11 on 2026-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('ALFA', 'Alfa'), ('BETA', 'Beta'), ('GAMA', 'Gama')], max_length=10)),
                ('team', models.CharField(choices=[('DIS', 'Dış Organizasyonlar'), ('IC', 'İç Organizasyonlar'), ('IK', 'İnsan Kaynakları'), ('FIN', 'Finans'), ('GAMA', 'Gama Kurulu')], max_length=10)),
                ('image', models.ImageField(default='team/default.png', upload_to='team/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
