# Generated by Django 6.0.1 on 2026-01-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Etkinlik AdÄ±')),
                ('description', models.TextField(verbose_name='Etkinlik AÃ§Ä±klamasÄ±')),
                ('date', models.DateTimeField(verbose_name='Etkinlik Tarihi')),
                ('location', models.CharField(max_length=200, verbose_name='Yer')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Kapak FotoÄŸrafÄ±')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dergi AdÄ±')),
                ('semester', models.CharField(max_length=100, verbose_name='DÃ¶nem (Ã–rn: 2024-2025 GÃ¼z)')),
                ('cover_image', models.ImageField(upload_to='magazines/covers/', verbose_name='Kapak FotoÄŸrafÄ±')),
                ('pdf_file', models.FileField(upload_to='magazines/pdfs/', verbose_name='PDF DosyasÄ±')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Duyuru BaÅŸlÄ±ÄŸÄ±')),
                ('content', models.TextField(verbose_name='Ä°Ã§erik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='GÃ¶rsel (Opsiyonel)')),
                ('is_active', models.BooleanField(default=True, verbose_name='YayÄ±nda mÄ±?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_preference', models.CharField(max_length=200, verbose_name='Yer Ã–nerisi')),
                ('catering_preference', models.CharField(max_length=50, verbose_name='Ä°kram Tercihi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
