# Generated by Django 5.2.11 on 2026-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Dergi Başlığı')),
                ('issue_number', models.PositiveIntegerField(verbose_name='Sayı No')),
                ('release_date', models.DateField(verbose_name='Yayın Tarihi')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('cover_image', models.ImageField(upload_to='magazines/covers/', verbose_name='Kapak Resmi')),
                ('read_link', models.URLField(verbose_name='Okuma Linki (Issuu vb.)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='magazines/pdfs/', verbose_name='PDF Dosyası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Dergi',
                'verbose_name_plural': 'Dergiler',
                'ordering': ['-release_date'],
            },
        ),
    ]
