# Generated by Django 5.2.11 on 2026-05-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KALE', 'KALE'), ('SB', 'Sektör Günleri'), ('SG', 'Şirket Günleri'), ('TG', 'Teknik Gezi'), ('ES', 'Eğitim Seminerleri'), ('GDKG', 'GDKG'), ('COL', 'COL'), ('MENT', 'Mentorship')], max_length=10, verbose_name='Organizasyon Tipi')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('title', models.CharField(max_length=255, verbose_name='Etkinlik Başlığı')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dinamik İçerik (JSON)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Şu anki Aktif Sayfa mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('type', 'year')},
            },
        ),
    ]
