# Generated by Django 5.2.11 on 2026-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ANLIK', 'Anlık Duyuru'), ('KULUP', 'Kulüpsel Gelişmeler'), ('ETKINLIK', 'Etkinlik Haberi')], default='ANLIK', max_length=10)),
                ('title', models.CharField(max_length=200, verbose_name='Duyuru Başlığı')),
                ('text', models.TextField(verbose_name='Duyuru İçeriği')),
                ('link', models.URLField(blank=True, verbose_name='Detay Linki (Opsiyonel)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-created_at'],
            },
        ),
    ]
