# Generated by Django 5.2.11 on 2026-05-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sponsor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationEvent',
        ),
    ]
