# Generated by Django 5.2.11 on 2026-05-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_organizationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SBArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('motto', models.CharField(max_length=255, verbose_name='Yılın Mottosu')),
                ('cover_image', models.ImageField(upload_to='sb/covers/', verbose_name='Kapak Görseli')),
                ('description', models.TextField(verbose_name='Yıl Özeti')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.organizationevent')),
            ],
            options={
                'verbose_name': 'SB Arşivi',
                'ordering': ['-year'],
            },
        ),
    ]
