# Generated by Django 5.2.11 on 2026-05-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organizationevent_sbarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('motto', models.CharField(max_length=255, verbose_name='Dönem Mottosu / Sloganı')),
                ('description', models.TextField(verbose_name='Dönem Özeti')),
                ('cover_image', models.ImageField(upload_to='org/covers/')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.organizationevent')),
            ],
            options={
                'verbose_name': 'Organizasyon Arşivi',
                'ordering': ['-year'],
            },
        ),
        migrations.DeleteModel(
            name='SBArchive',
        ),
    ]
