# Generated by Django 5.2.11 on 2026-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organizationarchive_delete_sbarchive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AddField(
            model_name='announcement',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('ANLIK', 'Anlık Duyuru'), ('KULUP', 'Kulüpsel Gelişmeler'), ('ETKINLIK', 'Etkinlik Haberi'), ('EGITIM', 'Eğitim & Seminer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
